name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Run security audit
        run: bunx audit-ci --high

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: License Compliance Check
        uses: microsoft/license-compliance-action@v1
        with:
          config: |
            {
              "allowed": [
                "MIT",
                "Apache-2.0",
                "BSD-2-Clause",
                "BSD-3-Clause",
                "ISC"
              ],
              "forbidden": [
                "AGPL-1.0-or-later",
                "AGPL-3.0-or-later"
              ]
            }